sudo: required
services:
        - docker
before_install:
        - docker build -t unsmoker/docker-react  -f Dockerfile.dev .
script:
        - docker run unsmoker/docker-react npm run test -- --coverage
